#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

ANDROID_PLATFORM_VERSION=28
# x86 (i686)
ANDROID_BUILD_TARGET=i686-linux-android

# x86_64
# ANDROID_BUILD_TARGET=x86_64-linux-android

# arm64
# ANDROID_BUILD_TARGET=arm64-v8a

# armeabi
# ANDROID_BUILD_TARGET=armeabi-v7a

ANDROID_DIR=$DIR/../plugin/android
JNI_LIBS_DIR=$ANDROID_DIR/src/main/jniLibs

# Install Android NDK https://developer.android.com/studio/projects/install-ndk
# https://github.com/bbqsrc/cargo-ndk
cargo ndk                              \
  --platform $ANDROID_PLATFORM_VERSION \
  --target $ANDROID_BUILD_TARGET       \
  --output-dir $JNI_LIBS_DIR           \
  build
