matrix:
  include:
    # Job 1) Run tests
    - os: linux
      env:
        - SHARD=Tests
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid-fallback
      before_script:
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
      script:
        - cd charts_common
        # TODO  Enable travis to run charts common test after fixing timezone test bug.
        #- pub get
        #- pub run test
        - cd ../charts_flutter
        - flutter test

cache:
  directories:
    - $HOME/.pub-cache
