#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT=$DIR/..

cargo build --release --target wasm32-unknown-unknown --lib --target-dir target_wasm 

# https://rustwasm.github.io/docs/book/reference/code-size.html#use-the-wasm-opt-tool
WASM_INTERFACE_TYPES=1 wasm-opt -Oz -o   \
  $ROOT/todo_cubit.wasm \
  $ROOT/target_wasm/wasm32-unknown-unknown/release/todo_cubit.wasm  

cp $ROOT/todo_cubit.wasm $ROOT/build/web/todo_cubit.wasm
