#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

ROOT=$DIR/..

cd $ROOT && cargo run rid_build && \
cd $ROOT/plugin && flutter pub run wasmjsgen --verbose severe
cp $ROOT/plugin/lib/generated/rid_api.sav.dart $ROOT/plugin/lib/generated/rid_api.dart 
